paths:
  rulesets_path: {{ config.paths.rulesets }}
  recipes_path: {{ config.paths.recipes }}
  responses_path: {{ config.paths.responses }}

listeners: {% for listener in config.listeners %}
  - {{ listener }} {% endfor %}

extensions: {% for extension in config.extensions %}
  - {{ extension }} {% endfor %}

functions: {% for function in config.functions %}
  - {{ function }} {% endfor %}

internal:
  api:
    server.socket_port: {{ config.internal.api_port }}
  logging:
    log_level: {{ config.internal.log.level }}
    log_format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
    pretty_print: {{ config.internal.log.pretty }}